spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/baodan?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
      username: root
      password: 123
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/views/
    suffix: .html


mybatis:
  type-aliases-package: com.shuoxianren.baodan.entity
  mapper-locations: classpath:mapper/*.xml

#server:
#  servlet:
#    context-path: /comm/



